# Generated by Django 5.2.17 on 2026-09-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_normalize_account_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='insurance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
