# Generated by Django 6.1.1 on 2026-09-12 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_status_time_alter_appointment_options_and_more'),
        ('users', '0013_specialty_alter_doctors_specialty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-start_date'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_response',
            field=models.TextField(blank=True, null=True, verbose_name='Vrach javobi'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Javob berilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(verbose_name='Murojaat matni'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.doctors'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patients'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='summary',
            field=models.TextField(verbose_name='Murojaat mavzusi'),
        ),
    ]
