# Generated by Django 6.1.1 on 2026-09-12 07:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_appointment_options_and_more'),
        ('users', '0014_alter_specialty_options_reste_token_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-start_date', 'time__time'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['time'], 'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot_reserved',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='users.doctors'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_response',
            field=models.TextField(blank=True, default='', verbose_name='Vrach javobi'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='users.patients'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='summary',
            field=models.CharField(max_length=250, verbose_name='Murojaat mavzusi'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.time'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'start_date'], name='patients_ap_doctor__69a723_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'start_date'], name='patients_ap_patient_7c2291_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('slot_reserved', True)), fields=('doctor', 'start_date', 'time'), name='uniq_reserved_doctor_slot'),
        ),
    ]
