# Generated by Django 6.1.1 on 2026-09-12 07:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_blogs_thumbnail'),
        ('users', '0014_alter_specialty_options_reste_token_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-posted_at'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['commented_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='users.doctors'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='posted_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/thumbnail', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), users.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='doctors.blogs'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commented_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
